###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	pcle/cmdpcle.h \
	pcle/pcle.h \
	pcle/specie.h

preproc += 

sources += \
	pcle/specie.cxx

extrsrc += 
