###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	pcle/camspecie.h \
	pcle/cmdpcle.h \
	pcle/pcle.h \
	pcle/specie.h

# preproc +=

sources += \
	pcle/camspecie.cxx \
	pcle/specie.cxx

extrsrc += \
	pcle/DocSpecie.dox
