
# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colors dont work on some unixes
alias ll='ls -alF'
alias la='ls -A'
alias lfind="find . -name"
alias e="emacs -nw"
alias enw="emacs -nw"
alias duh="du -hs"
alias dfh="df -h"
alias su="su -"
alias jam="jam -j 2"
alias cmatlab="matlab -nodesktop -nosplash"
alias ushowq="showq -u `whoami`"
alias uqstat="qstat -u `whoami`"

export INPUTRC="$HOME/.inputrc"
export PATH="$HOME/bin:$HOME/install/bin:$PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/install/lib/:/usr/local/lib/"

# RED machine BLUE work_dir $ BLACK
PS1='\[\033[01;31m\]\h\[\033[01;34m\] \w \$\[\033[00m\] '

if [ -r /etc/bash_completion ]; then
        # Source completion code.
    . /etc/bash_completion
fi
