
# colors dont work on some unixes
#alias ls="ls --color=auto"
alias ll="ls -l"
alias lfind="find . -name"
alias e="emacs -nw"
alias enw="emacs -nw"
alias duh="du -hs"
alias dfh="df -h"
alias su="su -"
alias jam="jam -j 2"
alias make="make -j"

export INPUTRC=~/.inputrc
export PATH="~/bin:~/install/bin:$PATH"
export LD_LIBRARY_PATH=~/install/lib/:/usr/local/lib/

# RED machine BLUE work_dir $ BLACK
PS1='\[\033[01;31m\]\h\[\033[01;34m\] \w \$\[\033[00m\] '
