###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	rand/arms.h \
	rand/cos.h \
	rand/maxwell.h \
	rand/psd.h \
	rand/range.h \
	rand/rndgen.h \
	rand/sigmund.h \
	rand/sphere.h \
	rand/thompson.h

# preproc += \
# 	rand/.cpp

sources += \
	rand/arms.cxx \
	rand/cos.cxx \
	rand/maxwell.cxx \
	rand/psd.cxx \
	rand/range.cxx \
	rand/rndgen.cxx \
	rand/sigmund.cxx \
	rand/sphere.cxx \
	rand/thompson.cxx

# extrsrc += 
