###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	rand/maxwgen.h \
	rand/rndgen.h

# preproc += \
# 	rand/.cpp

sources += \
	rand/maxwgen.cxx \
	rand/rndgen.cxx

# extrsrc += 
