###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	omp/initomp.h

# lochdrs +=

# preproc +=

sources += \
	omp/initomp.cxx
