###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	misc/code.h

# preproc += \
# 	misc/init.cpp

sources += \
	misc/init.cxx
