###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	$(abs_srcdir)/misc/code.h

# preproc += \
# 	$(abs_srcdir)/misc/init.cpp

sources += \
	$(abs_srcdir)/misc/init.cxx
