
if HAVE_ZLIB
LDADD += $(ZLIB_LIBS)
endif

if HAVE_HDF5
CXXFLAGS += $(HDF5_CPPFLAGS)
LDFLAGS += $(HDF5_LDFLAGS)
LDADD += $(HDF5_LIBS)

if HAVE_H5PART
CXXFLAGS += $(H5PART_CPPFLAGS)
LDFLAGS += $(H5PART_LDFLAGS)
LDADD += $(H5PART_LIBS)
endif

endif

LDADD += $(libs_dir)/io/libsatio.a
