
include $(top_srcdir)/mk/amake/Makefile.first
include $(top_srcdir)/mk/amake/Makefile.base
include $(top_srcdir)/mk/amake/Makefile.pint
include $(top_srcdir)/mk/amake/Makefile.math
include $(top_srcdir)/mk/amake/Makefile.simul
include $(top_srcdir)/mk/amake/Makefile.code
include $(top_srcdir)/mk/amake/Makefile.io

all-local:
	@for i in $(EXTRA_DIST); do \
	  if test ! -f $$i; then \
	    ln -s $(srcdir)/$$i; \
	  fi \
	done
