###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	func/angle.h \
	func/faddeeva.h \
	func/plasmafnc.h \
 	func/stdmath.h

preproc += \
	func/angle.cpp \
	func/stdmath.cpp

sources += \
	func/faddeeva.cxx \
	func/plasmafnc.cxx

# extrsrc += 
