###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	$(abs_srcdir)/misc/convert.h \
	$(abs_srcdir)/misc/domain.h \
	$(abs_srcdir)/misc/hybridconv.h \
	$(abs_srcdir)/misc/loc.h \
	$(abs_srcdir)/misc/range.h \
	$(abs_srcdir)/misc/simtime.h

# preproc += 

sources += \
	$(abs_srcdir)/misc/convert.cxx \
	$(abs_srcdir)/misc/domain.cxx \
	$(abs_srcdir)/misc/hybridconv.cxx \
	$(abs_srcdir)/misc/range.cxx \
	$(abs_srcdir)/misc/simtime.cxx

# extrsrc += 
