###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	misc/convert.h \
	misc/domain.h \
	misc/hybridconv.h \
	misc/loc.h \
	misc/range.h \
	misc/simtime.h

# preproc += 

sources += \
	misc/convert.cxx \
	misc/domain.cxx \
	misc/hybridconv.cxx \
	misc/range.cxx \
	misc/simtime.cxx

# extrsrc += 
