###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	sensor/fldsens.h \
	sensor/sensmng.h \
	sensor/sensor.h

# preproc += 

sources += \
	sensor/sensmng.cxx \
	sensor/sensor.cxx

#extrsrc += 
