###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	xdmf/filexdmf.h \
	xdmf/hdf5types.h

preproc +=  \
	xdmf/filexdmf.cpp

sources += \
	xdmf/filexdmf.cxx

# extrsrc += 
