###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	misc/stdmath.h \
	misc/vector.h

preproc += \
	misc/stdmath.cpp \
	misc/vector.cpp

# sources += \
# 	misc/stdmath.cxx

# extrsrc += 
