
headers += \
	tester/checks.h \
	tester/details.h \
	tester/exception.h \
	tester/info.h \
	tester/macros.h \
	tester/repdeferred.h \
	tester/reporter.h \
	tester/repstdout.h \
	tester/repxml.h \
	tester/results.h \
	tester/runner.h \
	tester/suite.h \
	tester/testbase.h \
	tester/tester.h \
	tester/testlist.h

sources += \
	tester/checks.cxx \
	tester/details.cxx \
	tester/exception.cxx \
	tester/info.cxx \
	tester/repdeferred.cxx \
	tester/repstdout.cxx \
	tester/repxml.cxx \
	tester/results.cxx \
	tester/runner.cxx \
	tester/testbase.cxx \
	tester/testlist.cxx
