
headers += \
	$(abs_srcdir)/tester/checks.h \
	$(abs_srcdir)/tester/details.h \
	$(abs_srcdir)/tester/exception.h \
	$(abs_srcdir)/tester/info.h \
	$(abs_srcdir)/tester/macros.h \
	$(abs_srcdir)/tester/repdeferred.h \
	$(abs_srcdir)/tester/reporter.h \
	$(abs_srcdir)/tester/repstdout.h \
	$(abs_srcdir)/tester/repxml.h \
	$(abs_srcdir)/tester/results.h \
	$(abs_srcdir)/tester/runner.h \
	$(abs_srcdir)/tester/suite.h \
	$(abs_srcdir)/tester/testbase.h \
	$(abs_srcdir)/tester/tester.h \
	$(abs_srcdir)/tester/testlist.h

sources += \
	$(abs_srcdir)/tester/checks.cxx \
	$(abs_srcdir)/tester/details.cxx \
	$(abs_srcdir)/tester/exception.cxx \
	$(abs_srcdir)/tester/info.cxx \
	$(abs_srcdir)/tester/repdeferred.cxx \
	$(abs_srcdir)/tester/repstdout.cxx \
	$(abs_srcdir)/tester/repxml.cxx \
	$(abs_srcdir)/tester/results.cxx \
	$(abs_srcdir)/tester/runner.cxx \
	$(abs_srcdir)/tester/testbase.cxx \
	$(abs_srcdir)/tester/testlist.cxx
