###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	misc/fmanip.h \
	misc/gzstream.h \
	misc/iomanager.h

preproc += \
	misc/iomanager.cpp

sources += \
	misc/fmanip.cxx \
	misc/gzstream.cxx \
	misc/iomanager.cxx

# extrsrc += 
