###############################################################################
##   Copyright (C) by Jan Paral and SAT team                                  #
##   See docs/license/sat file for copying and redistribution conditions.     #
###############################################################################

headers += \
	stw/filestw.h

preproc +=  \
	stw/filestw.cpp

# sources +=

# extrsrc += 
